### ISSUE TITLE
Infografia Las fases y gestion de proyectos 

### ISSUE THREAD

**Issue by luzm23** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-luzm23#1]
[Infografia Las fases y gestion de proyectos .pdf](https://github.com/user-attachments/files/16776228/Infografia.Las.fases.y.gestion.de.proyectos.pdf)

**Comment by Elisahadad** [comment]
Calificación = 20 
Muy Bien

**Comment by josealfredo79** [comment]
20 bien hecho y revisado..
